wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      localization_images_list_wandb_delimeter_predictions:
        type: bounding_box/class_labels
        key: localization_images_list_wandb_delimeter_predictions
        value:
          '0': circle
    python_version: 3.8.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685002680.875772
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.8.13
      5: 0.15.3
      8:
      - 3
      - 5
